### ISSUE TITLE
Scaffold component style issue

### ISSUE THREAD

**Issue by roszelj** [react-declarative/react-declarative#10]
It looks like the Scaffold component in the Context.tsx has "Scaffold" hard coded on line 160

**Comment by tripolskypetr** [comment]
The development of the original Scaffold component was started more than two years ago in [material-ui-umd](https://github.com/tripolskypetr/material-ui-umd/blob/f856b569dddfac127eca9ba24ec863fc603a6167/lib/form-tools/src/components/Scaffold.tsx) repo. Right now It definitely overcame it's architecture and It's time to refactor it

In [react-declarative@2.2.74](https://www.npmjs.com/package/react-declarative/v/2.2.74) I created a `Scaffold2` component which got a better user experience. The code is much cleaner, I think It is going to be useful for you to [check this MR](https://github.com/react-declarative/react-declarative/pull/12)

![screenshot1](https://user-images.githubusercontent.com/19227776/221436357-28a098bc-321b-4f27-a3ae-5cc1ec9f00c7.png)

![screenshot2](https://user-images.githubusercontent.com/19227776/221436180-0c876328-f010-4109-97a1-90187ca17307.png)
