### ISSUE TITLE
Minified d.ts files

### ISSUE THREAD

**Issue by phytonmk** [react-declarative/react-declarative#11]
Minification of `.d.ts` files doesn't affect final app performance while significantly downgrades explorability of library typings. As far as I know no other library performes typings minification and, I suppose, this one also should not do it. 

![Screen Shot 2023-02-24 at 15 15 22](https://user-images.githubusercontent.com/31261408/221200484-421ea75f-8441-43d3-9c82-329d658c5028.png)

**Comment by tripolskypetr** [comment]
Thanks for feedback. I have disabled the minification since [react-declarative@2.2.74](https://www.npmjs.com/package/react-declarative/v/2.2.74)
