### ISSUE TITLE
failed to build with docusaurus@latest

### ISSUE THREAD

**Issue by Ad-Bean** [react-declarative/react-declarative#14]
```json
  "dependencies": {
    "@docusaurus/core": "2.3.1",
    "@docusaurus/preset-classic": "2.3.1",
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@mdx-js/react": "^1.6.22",
    "@mui/icons-material": "^5.11.11",
    "@mui/lab": "5.0.0-alpha.123",
    "@mui/material": "^5.11.13",
    "clsx": "^1.2.1",
    "prism-react-renderer": "^1.3.5",
    "react": "^18.2.0",
    "react-declarative": "^2.2.115",
    "react-dom": "^18.2.0",
    "tss-react": "^4.8.2",
    "xlsx": "^0.18.5"
  },
```

when I tried to use `react-declarative` with `docusaurus@latest`, it failed to run `pnpm build` and got the following errors:

![image](https://user-images.githubusercontent.com/54789193/226791747-582d6517-df0f-47bc-ae6b-25a922d2bf00.png)

**Comment by tripolskypetr** [comment]
I have upgraded ESBuild. Maybe It will fix that issue...

![image](https://user-images.githubusercontent.com/19227776/226853148-36f9f601-1824-453c-b685-8f5fa8d0b047.png)

If this not going to help, try to remove `index.modern.js`.

![image](https://user-images.githubusercontent.com/19227776/226853503-232efc10-17d6-4ab9-85ab-75a0dc54ade3.png)

The docusaurus is working with CommonJS modules only so It should make a fallback

![image](https://user-images.githubusercontent.com/19227776/226854251-d701c5ba-de99-4cf2-9ef9-83023efb22b9.png)

If still not Ok, try to wrap you react-declarative widgets to [web-components](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) and [load them from custom library](https://www.fabiofranchino.com/blog/create-react-reusable-components-library-with-microbundle/). Write an issue in [ESBuild repository](https://github.com/evanw/esbuild)

```tsx
import { createWebComponent, One } from 'react-declarative';

createWebComponent("frontend-widget", (params) => (
    <One
      ...
    />
));

...

<frontend-widget />
```

**Comment by tripolskypetr** [comment]
See https://github.com/facebook/docusaurus/issues/6520.
