### ISSUE TITLE
Highlight "invalid" fields during the form submission

### ISSUE THREAD

**Issue by evgeny-s** [react-declarative/react-declarative#50]
## Description

This is more question, then the issue, but anyway.
Is there a possibility of highlighting (making the red color) all the "invalid" fields during the submission? Let's say I have 15 fields and half are invalid.

Thanks!

**Comment by tripolskypetr** [comment]
Hello! That functionality is built into the `react-declarative`, just use the dirty prop of `<One />` component

```tsx
import { One, FieldType, TypedField } from "react-declarative"

const fields: TypedField[] = [
        ...
]

...

<One
        dirty
//     ^^^^^
        fields={fields}
/>

```

The [dirty](https://formik.org/docs/api/formik#dirty-boolean) prop is inspired from Formik. Is set, that means that every field act as touched so they show the invalid state by default

**Comment by tripolskypetr** [comment]
Duplicate of https://github.com/react-declarative/react-declarative/issues/13
