### ISSUE TITLE
Is there a way to add price formatter (comma + decimal delimiter)?

### ISSUE THREAD

**Issue by evgeny-s** [react-declarative/react-declarative#54]
## Description
Hey, Petr.
Is there a way to add a price formatter (comma + decimal delimiter) to the number field?

Thanks!

https://github.com/user-attachments/assets/f970e591-845a-492b-b8f1-999a853bf736

<img width="263" alt="image" src="https://github.com/user-attachments/assets/48870bf2-5e6a-4271-9451-99792448b8d8">

**Comment by tripolskypetr** [comment]
There are two diffrent options for text value format in `react-declarative`. The first one is `inpurtFormatterTemplate`. This property allow you to format values like in official documents. For example, [SNILS](https://en.wikipedia.org/wiki/SNILS_(Russia)), `123-456-789 12`

```tsx
{
    type: FieldType.Text,
    title: 'Snils',
    name: 'snils',
    inputFormatterTemplate: '##-#-###-### ##',
    inputFormatterSymbol: '#',
    inputFormatterAllowed: /^[0-9]/,
}
```

Cause comma places are dynamic It is not suitable in your case, you should use `FieldType.Component` to inject the Amount field into form

```tsx
import { IField, FieldType, formatAmount } from "react-declarative";

import { TextField, InputAdornment } from '@mui/material';

const format = (value: string) => {
  if (!value) {
    return "";
  }
  return formatAmount(value);
}

export const fields: IField[] = [
  {
    type: FieldType.Component,
    name: 'quantity',
    element: ({
      value,
      onValueChange,
    }) => (
      <TextField
        value={value}
        variant="standard"
        onChange={({ target }) => onValueChange(format(target.value))}
        InputProps={{
            endAdornment: <InputAdornment position="end">$</InputAdornment>,
        }}
      />
    ),
  }
];

```

![image](https://github.com/user-attachments/assets/9fb435e8-4a35-407f-bf98-9ff7088b34df)

**P.S.** I just uploaded a new version so you should `npm install` it

**Comment by evgeny-s** [comment]
Thanks for the response. 
As usually quick and elegant. 
BTW, seems like `formatAmount` is not working properly, something for you to check:
<img width="998" alt="Zrzut ekranu 2024-08-9 o 18 12 18" src="https://github.com/user-attachments/assets/4da762e4-32e1-4185-93a1-035b23e16101">

**Comment by tripolskypetr** [comment]
@evgeny-s 

The `separator` argument helps you to change the `,` to `.` in decimals when you working with floats. I'l take a look on naming

![Screenshot_20240809_211912_Chrome (1).jpg](https://github.com/user-attachments/assets/fd8c8fb0-131a-455f-b44e-07f52c2f1325)

**Comment by tripolskypetr** [comment]
@evgeny-s Also, could you star that repo and share somewhere in social networks like Twitter (X), Linkedin? I am searching traffic for promotion, It would be great for SEO
